### ISSUE TITLE
I think we are breaking the DRY rule here

### ISSUE THREAD

**Issue by kostasx** [stachmatzidou/sha-dom-rock-paper-scissors#2]
https://github.com/stachmatzidou/sha-dom-rock-paper-scissors/blob/0b6693e7c8deef43dc080dd42e60388cd1365de0/script.js#L104

A lot of code is repeated here. Can we do better?

**Comment by stachmatzidou** [comment]
I think this is a vast improvement, but I still feel like there is more that can be done, especially in the finalResult function. I have tried refactoring it, but I can't get it to work. If you have any suggestions, I'd be more than happy to hear them.

**Comment by kostasx** [comment]
The following lines are executed for both if and else if statements:

```js
buttonRock.setAttribute("disabled", "");
buttonPaper.setAttribute("disabled", "");
buttonScissors.setAttribute("disabled", "");
```

What if we moved these into a function and called the function instead?

**Comment by stachmatzidou** [comment]
That's so simple and elegant. Thank you!
